name: Build, Release, and Deploy Frontend

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_model:
    name: Build Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Setup project
      # - Install Python dependencies
      - name: Setup project
        run: |
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('stopwords')"
      
      # Prepare the dataset
      - name: Preprocessing
        run: python -m src.preprocess

      # Train the model
      - name: Training
        run: python -m src.train --output-onnx=True

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Generate CHANGELOG.md
        run: npx changelogen --hideAuthorEmail --output CHANGELOG.md

      - name: Commit and push CHANGELOG.md
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): $GITHUB_REF_NAME" || echo "No changes to commit"
          git push origin HEAD:master

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: python-build
          path: ./models/

  build_frontend:
    name: Build Frontend
    needs: build_model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Python Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-build
          path: ./models/

      - name: View model
        run: ls -lh ./models/

      - name: Copy ONNX model to public folder
        run: |
          cp ./models/pipeline.onnx ./app/public/model/
          cp ./models/classes.json ./app/public/model/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
            version: 10
            cache: true

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: app/

      - name: Build frontend
        run: pnpm run browser:build
        working-directory: app/

      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ./app/dist/

  deploy_pages:
    name: Deploy to GitHub Pages
    needs: build_frontend
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download Frontend Dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./dist

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
